services:
  weaviate-node-1: # same as extended service to avoid reconfiguring cluster comm
    extends:
      file: $PWD/apps/weaviate/docker-compose-replication.yml
      service: weaviate-node-1
    container_name: weaviate-node-1
    environment:
      ASYNC_INDEXING: 'true'
      GRPC_MAX_MESSAGE_SIZE: '12000000'

  weaviate-node-2: # same as extended service to avoid reconfiguring cluster comm
    extends:
      file: $PWD/apps/weaviate/docker-compose-replication.yml
      service: weaviate-node-2
    container_name: weaviate-node-2
    environment:
      ASYNC_INDEXING: 'true'
      GRPC_MAX_MESSAGE_SIZE: '12000000'

  weaviate-node-3: # same as extended service to avoid reconfiguring cluster comm
    extends:
      file: $PWD/apps/weaviate/docker-compose-replication.yml
      service: weaviate-node-3
    container_name: weaviate-node-3
    environment:
      ASYNC_INDEXING: 'true'
      GRPC_MAX_MESSAGE_SIZE: '12000000'
    