version: '3.9'
services:
  weaviate-node-1: # same as extended service to avoid reconfiguring cluster comm
    extends:
      file: ./../weaviate/docker-compose-replication.yml
      service: weaviate-node-1
    container_name: weaviate-node-1
    environment:
      ASYNC_INDEXING: 'true'

  weaviate-node-2: # same as extended service to avoid reconfiguring cluster comm
    extends:
      file: ./../weaviate/docker-compose-replication.yml
      service: weaviate-node-2
    container_name: weaviate-node-2
    environment:
      ASYNC_INDEXING: 'true'

  weaviate-node-3: # same as extended service to avoid reconfiguring cluster comm
    extends:
      file: ./../weaviate/docker-compose-replication.yml
      service: weaviate-node-3
    container_name: weaviate-node-3
    environment:
      ASYNC_INDEXING: 'true'
    