---
services:
  weaviate:
    depends_on: [telemetry-sink]
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: semitechnologies/weaviate:${DOCKER_COMPOSE_VERSION}
    ports:
    - 8080:8080
    - 50051:50051
    volumes:
    - ./.docker_data/data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_API_BASED_MODULES: 'true'
      CLUSTER_HOSTNAME: 'node1'
      DISABLE_TELEMETRY: '${DISABLE_TELEMETRY:-}'
      TELEMETRY_URL: 'http://telemetry-sink:8080/weaviate-telemetry'
      PERSISTENCE_LSM_ACCESS_STRATEGY: "${PERSISTENCE_LSM_ACCESS_STRATEGY}"

  telemetry-sink:
    extends:
      file: ../telemetry-sink/docker-compose.yml
      service: telemetry-sink
...
