---
version: '3.4'
services:
  weaviate-node-1:
    image: semitechnologies/weaviate:${DOCKER_COMPOSE_VERSION}
    restart: on-failure:0
    ports:
      - "8080:8080"
      - "50051:50051"
    volumes:
    - ./.docker_data/data1:/var/lib/weaviate
    environment:
      QUERY_DEFAULTS_LIMIT: 20
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      CLUSTER_HOSTNAME: "node1"
      CLUSTER_GOSSIP_BIND_PORT: "7110"
      CLUSTER_DATA_BIND_PORT: "7111"
      RAFT_PORT: '8300'
      RAFT_INTERNAL_RPC_PORT: "8301"
      RAFT_JOIN: "node1:8300,node2:8300,node3:8300"
      RAFT_BOOTSTRAP_EXPECT: "3"
      DISABLE_TELEMETRY: 'true'
      DEFAULT_VECTORIZER_MODULE: "none"
      PERSISTENCE_LSM_ACCESS_STRATEGY: "${PERSISTENCE_LSM_ACCESS_STRATEGY}"
      FAST_FAILURE_DETECTION: 'true'
    networks:
      - weaviate-cluster-network

  weaviate-node-2:
    init: true
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    image: semitechnologies/weaviate:${DOCKER_COMPOSE_VERSION}
    ports:
      - 8081:8080
      - "50052:50051"
    volumes:
    - ./.docker_data/data2:/var/lib/weaviate
    restart: on-failure:0
    environment:
      LOG_LEVEL: 'debug'
      QUERY_DEFAULTS_LIMIT: 20
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      CLUSTER_HOSTNAME: 'node2'
      CLUSTER_GOSSIP_BIND_PORT: '7110'
      CLUSTER_DATA_BIND_PORT: '7111'
      CLUSTER_JOIN: 'weaviate-node-1:7110'
      RAFT_PORT: '8300'
      RAFT_INTERNAL_RPC_PORT: "8301"
      RAFT_JOIN: "node1:8300,node2:8300,node3:8300"
      RAFT_BOOTSTRAP_EXPECT: "3"
      DISABLE_TELEMETRY: 'true'
      CONTEXTIONARY_URL: contextionary:9999
      DEFAULT_VECTORIZER_MODULE: "none"
      PERSISTENCE_LSM_ACCESS_STRATEGY: "${PERSISTENCE_LSM_ACCESS_STRATEGY}"
      FAST_FAILURE_DETECTION: 'true'
    networks:
      - weaviate-cluster-network

  weaviate-node-3:
    init: true
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    image: semitechnologies/weaviate:${DOCKER_COMPOSE_VERSION}
    ports:
      - 8082:8080
      - "50053:50051"
    volumes:
    - ./.docker_data/data3:/var/lib/weaviate
    restart: on-failure:0
    environment:
      LOG_LEVEL: 'debug'
      QUERY_DEFAULTS_LIMIT: 20
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      CLUSTER_HOSTNAME: 'node3'
      CLUSTER_GOSSIP_BIND_PORT: '7110'
      CLUSTER_DATA_BIND_PORT: '7111'
      CLUSTER_JOIN: 'weaviate-node-1:7110'
      RAFT_PORT: '8300'
      RAFT_INTERNAL_RPC_PORT: "8301"
      RAFT_JOIN: "node1:8300,node2:8300,node3:8300"
      RAFT_BOOTSTRAP_EXPECT: "3"
      DISABLE_TELEMETRY: 'true'
      CONTEXTIONARY_URL: contextionary:9999
      DEFAULT_VECTORIZER_MODULE: "none"
      PERSISTENCE_LSM_ACCESS_STRATEGY: "${PERSISTENCE_LSM_ACCESS_STRATEGY}"
      FAST_FAILURE_DETECTION: 'true'
    networks:
      - weaviate-cluster-network

networks:
  weaviate-cluster-network:
    driver: bridge