---
version: '3.9'
services:
  weaviate-node-1:
    init: true
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: semitechnologies/weaviate:$WEAVIATE_VERSION
    ports:
    - 8080:8080
    - 6060:6060
    - 50051:50051
    restart: 'no'
    volumes:
      - ./data-node-1:/var/lib/weaviate
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      CLUSTER_HOSTNAME: 'node1' 
      CLUSTER_GOSSIP_BIND_PORT: '7100'
      CLUSTER_DATA_BIND_PORT: '7101'
      PERSISTENCE_LSM_ACCESS_STRATEGY: '${PERSISTENCE_LSM_ACCESS_STRATEGY}'
      REPLICATION_MINIMUM_FACTOR: 3
      GOMEMLIMIT: 2048MiB
    deploy:
      resources:
        limits:
          # used in a chaos pipeline that tries to get Weaviate
          # OOM-killed
          memory: 2048M
  weaviate-node-2:
    init: true
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: semitechnologies/weaviate:$WEAVIATE_VERSION
    ports:
    - 8081:8080
    - 6061:6060
    - 50052:50051
    restart: 'no'
    volumes:
      - ./data-node-2:/var/lib/weaviate
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      CLUSTER_HOSTNAME: 'node2' 
      CLUSTER_GOSSIP_BIND_PORT: '7100'
      CLUSTER_DATA_BIND_PORT: '7101'
      PERSISTENCE_LSM_ACCESS_STRATEGY: '${PERSISTENCE_LSM_ACCESS_STRATEGY}'
      REPLICATION_MINIMUM_FACTOR: 3
      CLUSTER_JOIN: 'weaviate-node-1:7100'
      GOMEMLIMIT: 2048MiB
    deploy:
      resources:
        limits:
          # used in a chaos pipeline that tries to get Weaviate
          # OOM-killed
          memory: 2048M
  weaviate-node-3:
    init: true
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: semitechnologies/weaviate:$WEAVIATE_VERSION
    ports:
    - 8082:8080
    - 6062:6060
    - 50053:50051
    restart: 'no'
    volumes:
      - ./data-node-3:/var/lib/weaviate
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      CLUSTER_HOSTNAME: 'node3' 
      CLUSTER_GOSSIP_BIND_PORT: '7100'
      CLUSTER_DATA_BIND_PORT: '7101'
      PERSISTENCE_LSM_ACCESS_STRATEGY: '${PERSISTENCE_LSM_ACCESS_STRATEGY}'
      REPLICATION_MINIMUM_FACTOR: 3
      CLUSTER_JOIN: 'weaviate-node-1:7100'
      GOMEMLIMIT: 2048MiB
    deploy:
      resources:
        limits:
          # used in a chaos pipeline that tries to get Weaviate
          # OOM-killed
          memory: 2048M
